[project]
name = "internetgovernance-resource-hub"
version = "0.1.0"
description = "Internet Governance Impact Resource Hub"
readme = "README.md"
requires-python = ">=3.14"

[project.optional-dependencies]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mike"
]
